# toml-docs-start lang-main
[ja]
    languageName = "日本語"
    title = "カエルアプリ工房"
    weight = 1
    [ja.params.head]
        tagline = "カエルアプリ工房"
    [ja.params.feature]
        link = "/about"
        caption = "自己紹介"
    [ja.params.footer]
        license = ""

[en]
    languageName = "English"
    title = "Frog's App Factory"
    weight = 2
    [en.params.head]
        tagline = "A Hugo Theme"
    [en.params.feature]
        link = "/en/about"
        caption = "About"
    [en.params.footer]
        license = ""

