# toml-docs-start lang-main
[ja]
    languageName = "日本語"
    title = "カエルの人"
    weight = 1
    hasCJKLanguage = true
    timezone = "Asia/Tokyo"
    [ja.params.head]
        tagline = "カエルの人"
    [ja.params.feature]
        link = "/about"
        caption = "About"
    [ja.params.footer]
        license = ""

[en]
    languageName = "English"
    title = "FrogApp"
    weight = 2
    timezone = "UTC"
    [en.params.head]
        tagline = "FrogApp"
    [en.params.feature]
        link = "/en/about"
        caption = "About"
    [en.params.footer]
        license = ""
