[main]
    separator = "-"
    description = "カエルの人のポートフォリオ兼ブログ"
    enableDarkMode = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    [main.externalLinks]
        cue = true
        tab = true
    [main.build]
        transpiler = "dartsass"

[modules]
    core = ["bootstrap", "flexsearch", "fontawesome"]
    optional = ["leaflet", "katex", "lottie"]
    excludeSCSS = ["bootstrap"]
    disableTemplate = ["katex"]
    [modules.katex]
        state = "defer"
    [modules.fontawesome]
        inline = true
        debug = true
        skipMissing = false


# toml-docs-start version
[docs]
    basePath = "_vendor/github.com/r-40021/new-portfolio-and-blog"
    github = "https://github.com/r-40021/new-portfolio-and-blog"
    release = "https://github.com/r-40021/new-portfolio-and-blog/releases/tag/"
# toml-docs-end version

[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = true # prevents a Goldmark warning when processing HTML comments (as used by markdownlint)

[home]
    sections = ["blog", "work", "info"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 4
        align = "start"

[navigation]
    anchor = true
    logo = "/img/icon.webp"
    color = "body"
    fixed = true
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "X"
    url = "https://x.com/share?text={title}&url={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "LINE"
    url = "https://social-plugins.line.me/lineit/share?url={url}"
    icon = "fab line"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[sections]
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = true
        homepage = 9

    [sections.work]
        title = "Works"
        sort = "title"
        reverse = false
        cols = 3
        header = "none"
        footer = "tags"
        homepage = 3
        breadcrumb = false

    [sections.info]
        title = "Contact & Privacy"
        sort = "linktitle"
        reverse = false
        cols = 2
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "none"
        style = "border-1 card-emphasize"
        homepage = 3
        
# toml-docs-end list        

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#2b8243"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    # themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    # themeFontPath = "/fonts" # local path
    purge = true
# toml-docs-end theme-colors

[schema]
    type = "Organization"
    name = "FrogApp"
    locale = "ja-JP"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    # github = "https://github.com/r-40021"
    section = "blog"
    [author]
        name = "FrogApp"
        # twitter = "https://twitter.com/markdumay"
        # linkedin = "https://www.linkedin.com/in/markdumay/"
        # github = "https://github.com/r-40021"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "ja-JP"

[comments]
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 
