---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/en/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/en/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: document
  path: content/en/about.md
  label: About
upload_dir: assets/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.92.2
  - HUGO_ENABLEGITINFO=true
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
version: 0.81.0
