backend:
  name: github
  repo: "r-40021/new-portfolio-and-blog"
  branch: main
  base_url: https://new-portfolio-and-blog.pages.dev/
  auth_endpoint: /api/auth
publish_mode: editorial_workflow
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/img/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /img/uploads
collections:
  - name: "blog"
    label: "blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Author", name: "author", widget: "hidden", default: "FrogApp"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", required: true}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", required: true}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
      - {label: "Photo Credits", name: "photoCredits", widget: "string", default: '<a href="https://unsplash.com/@username">Name</a>'}
      - {label: "Photo Source", name: "photoSource", widget: "string", default: '<a href="https://unsplash.com/photos/xxxxx">Unsplash</a>'}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}