[[main]]
  name = "About"
  url = "/en/about/"
  weight = 10

[[main]]
  name = "Works"
  url = "/en/works/"
  weight = 20

[[main]]
  name = "Blog"
  url = "/en/blog/"
  weight = 30

[[main]]
  name = "Tags"
  url = "/en/tags/"
  weight = 40

[[main]]
  name = "Privacy"
  url = "/en/privacy/"
  weight = 50

[[main]]
  name = "Contact"
  url = "/en/contact/"
  weight = 60