[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Works"
  url = "/works/"
  weight = 20

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 40

[[main]]
  name = "Privacy"
  url = "/privacy/"
  weight = 50

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 60