---
label: Blog post
hide_body: false
fields:
- type: text
  name: author
  label: author
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: list
  name: tags
  label: tags
- type: datetime
  name: date
  label: date
- type: file
  name: thumbnail
  label: thumbnail
- type: textarea
  name: credits
  label: credits
